export const dynamic = "force-static";

const XSL = `<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9">
  <xsl:output method="html" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html lang="id">
      <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>XML Sitemap</title>
        <style>
          body { font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; color: #333; margin: 0; padding: 0; background: #fff; }
          .wrap { max-width: 1100px; margin: 0 auto; padding: 40px 28px 64px; }
          h1 { font-size: 2.4rem; font-weight: 700; color: #545454; margin: 0 0 20px; }
          p.intro { font-size: 15px; line-height: 1.65; color: #333; margin: 0 0 14px; }
          a { color: #2288d6; text-decoration: none; }
          a:hover { text-decoration: underline; }
          .brand { color: #2288d6; font-weight: 700; }
          table { width: 100%; border-collapse: collapse; margin-top: 22px; font-size: 14px; }
          th { text-align: left; font-weight: 700; color: #333; border-bottom: 2px solid #ccc; padding: 10px 12px; }
          td { padding: 10px 12px; color: #333; vertical-align: top; }
          tbody tr:nth-child(odd) { background: #f5f5f5; }
          td.mod { color: #777; white-space: nowrap; }
          .count { font-size: 15px; color: #333; margin-top: 6px; }
        </style>
      </head>
      <body>
        <div class="wrap">
          <h1>XML Sitemap</h1>
          <p class="intro">Generated by <span class="brand">Nuansa Translator</span>, this is an XML Sitemap, meant for consumption by search engines.</p>
          <p class="intro">You can find more information about XML sitemaps on <a href="https://www.sitemaps.org/" target="_blank" rel="noopener">sitemaps.org</a>.</p>
          <xsl:apply-templates/>
        </div>
      </body>
    </html>
  </xsl:template>

  <xsl:template match="s:sitemapindex">
    <p class="count">This XML Sitemap Index file contains <xsl:value-of select="count(s:sitemap)"/> sitemaps.</p>
    <table>
      <thead><tr><th>Sitemap</th><th>Last Modified</th></tr></thead>
      <tbody>
        <xsl:for-each select="s:sitemap">
          <tr>
            <td><a href="{s:loc}"><xsl:value-of select="s:loc"/></a></td>
            <td class="mod"><xsl:value-of select="s:lastmod"/></td>
          </tr>
        </xsl:for-each>
      </tbody>
    </table>
  </xsl:template>

  <xsl:template match="s:urlset">
    <p class="count">This XML Sitemap contains <xsl:value-of select="count(s:url)"/> URLs.</p>
    <table>
      <thead><tr><th>URL</th><th>Last Modified</th></tr></thead>
      <tbody>
        <xsl:for-each select="s:url">
          <tr>
            <td><a href="{s:loc}"><xsl:value-of select="s:loc"/></a></td>
            <td class="mod"><xsl:value-of select="s:lastmod"/></td>
          </tr>
        </xsl:for-each>
      </tbody>
    </table>
  </xsl:template>
</xsl:stylesheet>
`;

export function GET() {
  return new Response(XSL, { headers: { "Content-Type": "text/xsl; charset=utf-8" } });
}
