<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
  exclude-result-prefixes="sitemap image">

  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>

  <xsl:template match="/">
    <html lang="id">
      <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>XML Sitemap — Nuansa Translator</title>
        <style>
          * { box-sizing: border-box; margin: 0; padding: 0; }
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; font-size: 14px; color: #333; background: #f5f5f5; }
          #header { background: #0b2942; color: #fff; padding: 20px 30px; display: flex; align-items: center; gap: 16px; }
          #header h1 { font-size: 20px; font-weight: 700; }
          #header p { font-size: 13px; opacity: .8; margin-top: 3px; }
          #content { max-width: 1100px; margin: 30px auto; padding: 0 20px; }
          .intro { background: #fff; border-left: 4px solid #2288d6; padding: 14px 18px; margin-bottom: 24px; border-radius: 4px; font-size: 13px; color: #555; line-height: 1.6; }
          table { width: 100%; border-collapse: collapse; background: #fff; border-radius: 6px; overflow: hidden; box-shadow: 0 1px 4px rgba(0,0,0,.08); }
          thead tr { background: #0b2942; color: #fff; }
          thead th { padding: 12px 16px; text-align: left; font-size: 12px; font-weight: 600; text-transform: uppercase; letter-spacing: .05em; }
          tbody tr:nth-child(even) { background: #fafafa; }
          tbody tr:hover { background: #eaf3fb; }
          tbody td { padding: 11px 16px; border-bottom: 1px solid #eee; font-size: 13px; vertical-align: middle; }
          tbody td a { color: #2288d6; text-decoration: none; word-break: break-all; }
          tbody td a:hover { text-decoration: underline; }
          .tag { display: inline-block; background: #e7f0fb; color: #2288d6; font-size: 11px; font-weight: 600; padding: 2px 8px; border-radius: 20px; }
          .count { color: #888; font-size: 12px; margin-left: 8px; }
          #footer { text-align: center; margin: 30px 0 20px; font-size: 12px; color: #aaa; }
        </style>
      </head>
      <body>
        <div id="header">
          <div>
            <h1>XML Sitemap</h1>
            <p>This sitemap is generated by Nuansa Translator — <a href="https://nuansatranslator.co.id" style="color:#9cc7ee">nuansatranslator.co.id</a></p>
          </div>
        </div>

        <div id="content">
          <p class="intro">
            This XML Sitemap is used by search engines such as Google to discover the pages on this website.
            It was generated by <strong>Nuansa Translator</strong>.
            You can find more information about XML sitemaps at <a href="https://sitemaps.org" target="_blank">sitemaps.org</a>.
          </p>

          <!-- SITEMAP INDEX -->
          <xsl:if test="//sitemap:sitemapindex">
            <table>
              <thead>
                <tr>
                  <th>Sitemap URL</th>
                  <th>Last Modified</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="//sitemap:sitemapindex/sitemap:sitemap">
                  <tr>
                    <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
                    <td><xsl:value-of select="sitemap:lastmod"/></td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>

          <!-- URL SET -->
          <xsl:if test="//sitemap:urlset">
            <table>
              <thead>
                <tr>
                  <th>URL</th>
                  <th>Priority</th>
                  <th>Change Frequency</th>
                  <th>Last Modified</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="//sitemap:urlset/sitemap:url">
                  <tr>
                    <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
                    <td><xsl:value-of select="sitemap:priority"/></td>
                    <td><xsl:value-of select="sitemap:changefreq"/></td>
                    <td><xsl:value-of select="sitemap:lastmod"/></td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>
        </div>

        <div id="footer">Generated by Nuansa Translator · <a href="https://nuansatranslator.co.id">nuansatranslator.co.id</a></div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
